In [1]:
par =int(input("1.Choose 1 for Even parity \n 2. Choose 2 for Odd parity\n "))

print("Menu:\n 1.Choose 1 for Even parity \n 2. Choose 2 for Odd parity\n ")
print(f"You chose option {par}")



import numpy as np
seq = input("Enter the sequence: ")
#print(type(seq))
#print(seq)
m = len(seq)
r = 0

# finding out the r value
for i in range(10):
    x = m+i+1
    y = 2**i
    if y>=x:
        print(i)
        r = i
        break 
    

total_len = m+r

print(total_len)
arr = np.full(total_len,77) # 0 is the default value

p = 0
#i = 2**p
bit_pos=[]

# placing dummy values in the par positions
while i <= total_len-1:
    
    i = 2 ** p
    #print(i)
    if i<total_len:
        arr[i - 1] = 65
        bit_pos.append(i-1)
        

        
    p+=1
    
print(bit_pos)

binaryy=[]

#making the par pos as bin values
binaryy = [bin(i+1)[2:] for i in range(total_len)]

binaryy = [binary.zfill(r) for binary in binaryy]

#print(binaryy)
#print(binaryy)


#print(i)
#print(p)

print(arr)

len_arr =len(arr)
# placing the data bits in the array 
j = 0
l=0
while l<m:
    #print("value of l")
    #print(l)
    #print("val of len_arr-1-j")
    #print(len_arr-1-j)
    if arr[len_arr-1-j] == 77:
        arr[len_arr-1-j] = seq[l]
        l+=1
    else:
        l=l
    j += 1

print(arr)
    

    


def evenpar(seq,r,binaryy,arr):
         
    j = 0
    l=0
    #one=0

    Pos=[]
    R=[]
    i=0
    while i<r:
        #print("im in")
        pos=[]
        rr=[]
        #one=0
        #R.append(rr)
        #Pos.append(pos)
        for j in range(len(binaryy)):
            #pos=[]
            #print("2nd too")
            #print(binaryy[j][r-1-i])
            if int(binaryy[j][r-1-i]) == 1:
                #print("satisfied")
                pos.append(j)
                #print(pos)
            
    
            
            one = 0
            for k in pos:
                if arr[k] == 1:
                    one+=1
                else:
                    one+=0
            
        if one % 2 == 0:
            rr.append(0)
        else:
            rr.append(1)
        R.append(rr)
        Pos.append(pos)
        
        i+=1
            
    

#print(arr)
    print(R)
    print(Pos)
    return R


def oddpar(seq,r,binaryy,arr):
         
    j = 0
    l=0
    #one=0

    Pos=[]
    R=[]
    i=0
    while i<r:
        #print("im in")
        pos=[]
        rr=[]
        #one=0
        #R.append(rr)
        #Pos.append(pos)
        for j in range(len(binaryy)):
            #pos=[]
            #print("2nd too")
            #print(binaryy[j][r-1-i])
            if int(binaryy[j][r-1-i]) == 1:
                #print("satisfied")
                pos.append(j)
                #print(pos)
            
    
            
            one = 0
            for k in pos:
                if arr[k] == 1:
                    one+=1
                else:
                    one+=0
            
        if one % 2 == 0:
            rr.append(1)
        else:
            rr.append(0)
        R.append(rr)
        Pos.append(pos)
        
        i+=1
            
    

#print(arr)
    print(R)
    print(Pos)
    return R

#Rr =evenpar(seq,r,binaryy,arr)

if par ==1:
    Rr =evenpar(seq,r,binaryy,arr)
else:
    Rr = oddpar(seq,r,binaryy,arr)

ll=0
for kk in range(len(arr)):
    
    if arr[kk] == 65:
        arr[kk]=Rr[ll][0]
        ll+=1
    else:
       ll=ll
        
        
print(f"Your input sequence is : {seq}")
print(f"The hamming code for your choice is: ")
print(arr[::-1])        
            
    
         
        
        
    
    
    
    


        
    
  




Menu:
 1.Choose 1 for Even parity 
 2. Choose 2 for Odd parity
 
You chose option 1
4
11
[0, 1, 3, 7]
[65 65 77 65 77 77 77 65 77 77 77]
[65 65  1 65  0  1  1 65  0  0  1]
[[1], [0], [0], [1]]
[[0, 2, 4, 6, 8, 10], [1, 2, 5, 6, 9, 10], [3, 4, 5, 6], [7, 8, 9, 10]]
Your input sequence is : 1001101
The hamming code for your choice is: 
[1 0 0 1 1 1 0 0 1 0 1]


In [1]:
def hamming_code(inp,par):
    M = len(inp) #no of data bits 
    inp_lis = list(inp)
    #no of parity bits = no of blocks we create
    for i in range(1,M):
        lhs = 2**i
        rhs = M + i + 1
        if lhs >= rhs:
            R = i
            break
    N = M+R
    bit_pos = []
    parity = []
    for j in range(1,N+1):
        if ifpow(j):
            parity +=[j]
        bit_pos+=[dec2bini(j)]
    hamham = ["L"]*N
    for p in parity:
        hamham[p-1]="P"
    for l in range(0,N):
         if hamham[l]=="L" and hamham[l]!="P":
             hamham[l]=inp_lis.pop(0)
    p_val = {}
    
    for p in range(0,len(parity)):
        parv = []
        C = 0
        for pv in range(0,N):
            if bit_pos[pv][-1-p]=='1':
                parv+=[pv]
        print(parv)
        for h in parv:
            if hamham[h]=='1':
                C+=1
        print(C)
        if par==1:
            if C%2 == 0:
                p_val[parity[p]-1]='1'
            else: 
                p_val[parity[p]-1]='0'
        if par == 2:
            if C%2 != 0:
                p_val[parity[p]-1]='1'
            else: 
                p_val[parity[p]-1]='0'
    print(p_val)
    for i in p_val:
        hamham[i] = p_val[i]
    return hamham

In [1]:
def generate_hamming_code(data_word):
    # number of parity bits required
    r = 0
    while 2**r < len(data_word) + r + 1:
        r += 1
    
    #  Hamming code with parity bits set to 0
    hamming_code = [0] * (len(data_word) + r)
    j = 0
    
    for i in range(len(hamming_code)):
        if i+1 not in [2**x for x in range(r)]:
            hamming_code[i] = int(data_word[j])
            j += 1
    
    for i in range(r):
        parity_index = 2**i - 1
        count = 0
        for j in range(len(hamming_code)):
            if (j+1) & (1 << i):
                count += hamming_code[j]
        if count % 2 == 0:
            hamming_code[parity_index] = 0
        else:
            hamming_code[parity_index] = 1
            
    return hamming_code

def decode_hamming_code(received_code):
    r = 0
    while 2**r < len(received_code):
        r += 1
    
    # Initialize error position and syndrome
    error_pos = -1  # Initialize with -1 to indicate no error found
    syndrome = 0
    
    # syndrome
    for i in range(r):
        parity_index = 2**i - 1
        count = 0
        for j in range(len(received_code)):
            if (j+1) & (1 << i):
                count += received_code[j]
        if count % 2 != received_code[parity_index]:
            syndrome += 2**i
    
    # error check
    if syndrome != 0:
        error_pos = syndrome - 1
    
    # Correct error if any
    if error_pos != -1:
        received_code[error_pos] ^= 1
    
    # Extract and return the data bits
    data_word = ""
    j = 0
    for i in range(len(received_code)):
        if i+1 not in [2**x for x in range(r)]:
            data_word += str(received_code[i])
    
    return data_word
#input
data_word = input("Enter the data word (7 bits): ")
print("User input (data word):", data_word)

# Hamming code
hamming_code = generate_hamming_code(data_word)
print("Hamming code:", hamming_code)

# Decoded
decoded_data_word = decode_hamming_code(hamming_code)
print("Decoded data word:", decoded_data_word)

User input (data word): 100110
Hamming code: [1, 0, 1, 1, 0, 0, 1, 1, 1, 0]


IndexError: list index out of range